rules:
  - id: py-dangerous-eval-exec
    message: Dangerous code execution via eval/exec
    severity: ERROR
    languages: [python]
    pattern-either:
      - pattern: eval(...)
      - pattern: exec(...)

  - id: py-subprocess-shell-true
    message: subprocess called with shell=True (command injection risk)
    severity: ERROR
    languages: [python]
    pattern-either:
      - pattern: subprocess.run(..., shell=True, ...)
      - pattern: subprocess.Popen(..., shell=True, ...)
      - pattern: subprocess.call(..., shell=True, ...)

  - id: py-os-system
    message: os.system executes a shell command
    severity: ERROR
    languages: [python]
    pattern: os.system(...)

  - id: py-yaml-unsafe-load
    message: yaml.load without SafeLoader is unsafe
    severity: ERROR
    languages: [python]
    pattern: yaml.load(...)
    pattern-not: yaml.load(..., Loader=yaml.SafeLoader, ...)

  - id: py-pickle-unsafe-deserialization
    message: Unsafe deserialization via pickle/dill/marshal/joblib
    severity: ERROR
    languages: [python]
    pattern-either:
      - pattern: pickle.loads(...)
      - pattern: pickle.load(...)
      - pattern: dill.loads(...)
      - pattern: dill.load(...)
      - pattern: marshal.loads(...)
      - pattern: joblib.load(...)

  - id: py-requests-verify-false
    message: requests call disables SSL verification (verify=False)
    severity: WARNING
    languages: [python]
    patterns:
      - pattern: requests.$FUNC(..., verify=False, ...)

  - id: py-plain-http-request
    message: Plain HTTP request used
    severity: WARNING
    languages: [python]
    patterns:
      - pattern: requests.$FUNC($URL, ...)
      - metavariable-pattern:
          metavariable: $URL
          patterns:
            - pattern-regex: '^"http://'

  - id: py-spark-sql-fstring
    message: spark.sql uses f-string or string interpolation (SQL injection risk)
    severity: ERROR
    languages: [python]
    patterns:
      - pattern-regex: 'spark\\.sql\\s*\\(\\s*f[\'\"]'

  - id: py-dbutils-secret-printed
    message: Secret value printed or logged
    severity: ERROR
    languages: [python]
    pattern-either:
      - pattern: print(dbutils.secrets.get(...))
      - pattern: logging.info(dbutils.secrets.get(...))
      - pattern: logging.debug(dbutils.secrets.get(...))

